"""Build the standalone owner review for the single local full-song proof."""
from pathlib import Path
import json

base=Path('audio/x3/music')
data=dict(acceptance=json.loads((base/'acceptance.json').read_text()),
          first=json.loads((base/'first-pass/acceptance.json').read_text()),
          timeline=json.loads((base/'timeline.json').read_text()),cost=json.loads((base/'cost-plan.json').read_text()))
page='''<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Death Ride · one full-song proof</title>
<style>
:root{color-scheme:dark;--bg:#151714;--panel:#21251f;--text:#f0eddf;--muted:#b6baad;--line:#454b3e;--accent:#efbd70;--ok:#b3db9c;--fail:#ffaf99}
body.light{color-scheme:light;--bg:#f5f0e5;--panel:#fffaf0;--text:#24291f;--muted:#59604e;--line:#c5c8b9;--accent:#825215;--ok:#356a28;--fail:#9a3424}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:16px/1.55 system-ui,sans-serif}main{max-width:1080px;margin:auto;padding:36px 24px 60px}
header{display:flex;justify-content:space-between;align-items:center;gap:16px;border-bottom:1px solid var(--line);padding-bottom:18px}.eyebrow{font-size:12px;letter-spacing:.15em;text-transform:uppercase;color:var(--muted)}h1{font-size:clamp(32px,5vw,60px);line-height:1.04;max-width:800px;margin:30px 0 16px;font-weight:650}h2{font-size:24px;margin:32px 0 12px}h3{font-size:18px;margin:8px 0}.lede{font-size:19px;max-width:820px}.muted,small{color:var(--muted)}a{color:var(--accent);overflow-wrap:anywhere}button,textarea,select{font:inherit}button,select{background:var(--panel);color:var(--text);border:1px solid var(--line);border-radius:5px;padding:9px 13px;cursor:pointer}button:hover,button:focus-visible{border-color:var(--accent)}button:focus-visible,a:focus-visible,textarea:focus-visible{outline:2px solid var(--accent);outline-offset:3px}.tag{display:inline-block;margin:0 10px 8px 0;color:var(--accent)}.pass{color:var(--ok)}.fail{color:var(--fail)}.player{background:var(--panel);border:1px solid var(--line);padding:20px;margin-top:24px}.player audio{width:100%;margin:16px 0 0}canvas{width:100%;height:130px;display:block}.sections{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:12px}.sections button{padding:10px 6px;font-size:14px}.sections small{display:block}#now{font-variant-numeric:tabular-nums;color:var(--accent)}.trackline{display:flex;justify-content:space-between;gap:12px;align-items:center}.columns{display:grid;grid-template-columns:1fr 1fr;gap:32px}.entry{border-top:1px solid var(--line);padding:14px 0}.entry p{margin:6px 0}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;border-bottom:1px solid var(--line);padding:9px 6px}th{color:var(--muted)}details{padding:14px 0;border-top:1px solid var(--line)}summary{cursor:pointer;color:var(--accent)}details audio{width:100%;margin:12px 0}textarea{width:100%;min-height:110px;background:var(--panel);color:var(--text);border:1px solid var(--line);padding:12px;border-radius:4px}.actions{display:flex;gap:10px;flex-wrap:wrap;margin:12px 0}.foot{border-top:1px solid var(--line);padding-top:22px;margin-top:32px;font-size:14px}#notes-status{min-height:24px;color:var(--muted)}
@media(max-width:650px){main{padding:22px 16px 40px}.columns{grid-template-columns:1fr;gap:0}.sections{grid-template-columns:repeat(3,1fr)}.player{padding:13px}.trackline{align-items:flex-start}.lede{font-size:17px}header{font-size:14px}th,td{padding:7px 3px;font-size:12px}}
</style>
<main><header><div><strong>DEATH RIDE</strong><div class="eyebrow">Audio X3 · full-song research</div></div><button id="theme" aria-label="Toggle light or dark theme">Light / dark</button></header>
<h1>Dust road,<br>unpaid miles.</h1><p class="lede">One original 2½-minute instrumental in direction 01, Dust and drums. A locally composed proof of a changing song structure, with echo guitar synthesis, deep toms and sparse mechanical percussion.</p>
<div><span class="tag">150 seconds</span><span class="tag">96 BPM · D minor</span><span class="tag">0 provider credits</span><span class="tag">Owner listening pending</span></div>
<p class="muted">This is a synthesized arrangement proof. It does not establish the quality of a new ElevenLabs full-song take, and it is not installed as race music. The full paid set is planned for after the credit reset.</p>
<section class="player" aria-label="Proof song"><div class="trackline"><div><strong>Final master</strong><div class="pass" id="meter"></div></div><button id="stop">Stop all</button></div>
<canvas id="wave" role="img" aria-label="Song energy across intro, verse, peak, break and outro"></canvas><div id="now" aria-live="off">0:00 / 2:30 · Intro</div>
<audio id="main-player" controls preload="metadata" src="dust-road-proof.mp3"></audio><div class="sections" id="sections" aria-label="Jump to a section"></div></section>
<div class="columns"><section><h2>Hear the development</h2><div id="chapters"></div></section><section><h2>Signal acceptance</h2><p id="accept"></p><table><thead><tr><th>Join</th><th>Jump</th><th>Level step</th><th>Screen</th></tr></thead><tbody id="joins"></tbody></table>
<p class="muted">The four joins use 625 ms crossfades and composed transition notes. Limits declared before rendering: sample jump ≤0.02 full scale and 50 ms level step ≤6 dB. End-to-start looping is not applicable to this linear song.</p>
<p id="structure"></p><p class="muted">These checks do not judge musical interest, style fidelity, masking or fatigue. Please use the full playback and section buttons to assess those.</p>
<p><a href="dust-road-proof.flac">Download lossless master</a> · <a href="acceptance.json">Measurements</a> · <a href="score.json">Original score and provenance</a></p></section></div>
<h2>Retained evidence</h2><details><summary>First render · three transition level failures</summary><p>The same composition before four pitched transition tails were added. Intro→verse, verse→peak and break→outro failed the declared 6 dB level-step limit. Loudness and true peak passed. No paid reroll and no relaxed threshold.</p><audio controls preload="none" src="first-pass/dust-road-proof.mp3"></audio><a href="first-pass/acceptance.json">First measurements</a></details>
<details><summary>Unmatched score export · quieter than the master</summary><p>The final local arrangement before two-pass loudness matching. This is source evidence for the same composition, not a second proof track.</p><audio controls preload="none" src="dust-road-score.flac"></audio></details>
<h2>After the reset</h2><p>Six proposed songs, two each in styles 01, 02 and 03. All start as 120-second structured single takes, then use local edits if needed. Earliest account reset: <strong>4 October 2026, 19:31:41 UTC</strong>.</p>
<div class="columns"><div><strong>43,200 credits · base estimate</strong><p class="muted">54,000 including the bounded repair allowance. Keep 8,000 untouched: at least 62,000 live credits plus the agreed Garden VR allowance are needed for the full plan. The reset balance is not assumed.</p></div><div><strong>Start with one song per style</strong><p class="muted">First stage: 21,600 base, 27,000 with repairs. Review those before commissioning the second three. All six dry runs made zero network requests. Nothing is scheduled.</p></div></div>
<p><a href="cost-plan.json">Full cost plan and six dry runs</a> · <a href="RESEARCH.md">Method, sources and run instructions</a></p>
<h2>Owner listening notes</h2><label for="decision">Proof verdict</label> <select id="decision"><option>Not reviewed</option><option>Useful structure, refine sound</option><option>Keep this direction</option><option>Rework the composition</option></select>
<p><label for="notes">Notes on interest over 150 seconds, transition feel, guitar/drum balance and fatigue</label></p><textarea id="notes" placeholder="Add listening notes; nothing is sent anywhere."></textarea><div class="actions"><button id="export">Export notes</button><a href="../effects/index.html">Effects</a><a href="../engines/index.html">Ten-class engine triage</a><a href="../voices/index.html">Campaign voices</a></div><div id="notes-status" role="status"></div>
<div class="foot">Original local composition; no imported samples or artist imitation. Credits for all paid X3 waves remain 6,400 conservatively charged against the 9,000 cap. One held voice, engine choices, collision preference and physical Stick listening remain open.</div></main>
<script id="data" type="application/json">__DATA__</script><script>
const data=JSON.parse(document.querySelector('#data').textContent),row=data.acceptance.samples[0],metric=row.edited,sections=data.timeline.sections;
const $=s=>document.querySelector(s),player=$('#main-player'),time=s=>Math.floor(s/60)+':'+String(Math.floor(s%60)).padStart(2,'0');
$('#meter').textContent=`${metric.integratedLufs.toFixed(2)} LUFS · ${metric.truePeakDbtp.toFixed(2)} dBTP · technical ${metric.status}`;
$('#accept').textContent=`Full decode, 150-second duration, loudness, true peak, silence, clipping and all four joins: ${metric.status}. MP3 preview: ${row.preview.status}.`;
$('#structure').textContent=`60 individually rendered bars, ${data.acceptance.structure.identicalPcmBars} identical PCM bars. Peak: ${data.acceptance.structure.peakEventsPerBar} scored events/bar; break: ${data.acceptance.structure.breakEventsPerBar}. Distinct section energy is measured; listening is still required.`;
for(const s of sections){const b=document.createElement('button');b.innerHTML=`${s.name}<small>${time(s.start)}</small>`;b.onclick=()=>{player.currentTime=s.start;player.play().catch(()=>{});draw()};$('#sections').append(b);const d=document.createElement('div');d.className='entry';d.innerHTML=`<h3>${time(s.start)}–${time(s.end)} · ${s.name}</h3><p>${s.description}</p><small>${s.bars} bars · ${s.rmsDbfs.toFixed(1)} dBFS section RMS</small>`;$('#chapters').append(d)}
for(const j of metric.sectionJoins){const tr=document.createElement('tr');tr.innerHTML=`<td>${time(j.atSeconds)} ${j.into}</td><td>${j.sampleJumpFullScale.toFixed(4)}</td><td>${j.rmsStepDb.toFixed(2)} dB</td><td class="pass">${j.status}</td>`;$('#joins').append(tr)}
const canvas=$('#wave'),ctx=canvas.getContext('2d');
function draw(){const ratio=devicePixelRatio||1,w=canvas.clientWidth,h=130;canvas.width=w*ratio;canvas.height=h*ratio;ctx.scale(ratio,ratio);const css=getComputedStyle(document.body);ctx.fillStyle=css.getPropertyValue('--panel');ctx.fillRect(0,0,w,h);for(let i=0;i<sections.length;i++){const s=sections[i];ctx.globalAlpha=i%2?.12:.05;ctx.fillStyle=css.getPropertyValue('--accent');ctx.fillRect(s.start/150*w,0,(s.end-s.start)/150*w,h)}ctx.globalAlpha=1;const e=data.timeline.energyEnvelope20ms,max=Math.max(...e);ctx.strokeStyle=css.getPropertyValue('--accent');ctx.lineWidth=1;ctx.beginPath();for(let x=0;x<w;x++){const a=Math.floor(x/w*e.length),b=Math.max(a+1,Math.floor((x+1)/w*e.length));let v=0;for(let j=a;j<b;j++)v=Math.max(v,e[j]||0);const size=v/max*52;ctx.moveTo(x,65-size);ctx.lineTo(x,65+size)}ctx.stroke();ctx.strokeStyle=css.getPropertyValue('--text');ctx.beginPath();ctx.moveTo(player.currentTime/150*w,0);ctx.lineTo(player.currentTime/150*w,h);ctx.stroke();const s=sections.filter(s=>s.start<=player.currentTime).at(-1)||sections[0];$('#now').textContent=`${time(player.currentTime)} / 2:30 · ${s.name}`}
for(const a of document.querySelectorAll('audio'))a.addEventListener('play',()=>{for(const b of document.querySelectorAll('audio'))if(a!==b)b.pause()});
$('#stop').onclick=()=>{for(const a of document.querySelectorAll('audio')){a.pause();a.currentTime=0}draw()};player.ontimeupdate=draw;window.onresize=draw;
let saved={};try{saved=JSON.parse(localStorage.getItem('deathride-x3-song')||'{}')}catch{}
document.body.classList.toggle('light',!!saved.light);$('#notes').value=saved.notes||'';$('#decision').value=saved.decision||'Not reviewed';
function draft(){return{proof:'dust-road-proof',sha256:metric.sha256,decision:$('#decision').value,notes:$('#notes').value,light:document.body.classList.contains('light')}}
function save(){try{localStorage.setItem('deathride-x3-song',JSON.stringify(draft()));$('#notes-status').textContent='Saved in this browser only.'}catch{$('#notes-status').textContent='Browser storage unavailable; use Export notes.'}}
$('#theme').onclick=()=>{document.body.classList.toggle('light');save();draw()};$('#notes').oninput=save;$('#decision').onchange=save;
$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({...draft(),exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='deathride-x3-song-notes.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};draw();
</script></html>'''
(base/'index.html').write_text(page.replace('__DATA__',json.dumps(data).replace('</','<\\/')),encoding='utf-8',newline='\n')
print((base/'index.html').resolve().as_uri())
