(() => {
  'use strict';
  const data = window.TRACK_ATLAS, $ = id => document.getElementById(id);
  if (!data) { $('courses').textContent = 'Report data missing. Run :core:trackQualityReport from deathride, then reopen this page.'; return; }
  const make = (tag, text, attrs = {}) => { const n = document.createElement(tag); if (text !== undefined && text !== null) n.textContent = text; for (const [k, v] of Object.entries(attrs)) n.setAttribute(k, v); return n; };
  const num = (x, digits = 2) => Number.isFinite(x) ? x.toFixed(digits) : 'unmeasured';
  const gates = row => [...row.geometryGates, ...row.simulation.gates];
  const flags = row => gates(row).filter(g => g.status !== 'pass');
  const table = (heads, rows) => { const wrap = make('div', '', {class: 'table-wrap'}), t = make('table'), header = make('tr'), head = make('thead'), body = make('tbody'); heads.forEach(h => header.append(make('th', h))); head.append(header); rows.forEach(r => { const tr = make('tr'); r.forEach(x => tr.append(make('td', x))); body.append(tr); }); t.append(head, body); wrap.append(t); return wrap; };
  const details = (label, ...children) => { const d = make('details'); d.append(make('summary', label), ...children); return d; };
  const summary = [['25 + 1', 'courses + shared arena view'], [data.courses.reduce((n, c) => n + c.simulation.trialCount, 0).toLocaleString(), 'AI-only six-car races'], [data.gateProof.filter(p => p.fired).length, 'gate witnesses'], [data.courses.filter(c => flags(c).length).length, 'views with design flags']];
  summary.forEach(([value, label]) => { const box = make('div'); box.append(make('strong', value), make('span', label)); $('summary').append(box); });
  $('provenance').textContent = `${data.version} · ${data.generatedDate} · gameplay data SHA-256 ${data.gameplayContentDigest}. ${data.seedCount} seeds × ${data.rotations} rotations per view.`;
  [...new Set(data.courses.map(c => c.course.theme))].sort().forEach(theme => $('theme-filter').append(make('option', theme, {value: theme})));
  const views = [];
  for (const row of data.courses) {
    const g = row.geometry, m = g.metrics, sim = row.simulation, sm = sim.metrics, failed = flags(row);
    const tr = make('tr'), cell = make('td'), link = make('a', row.name, {href: `#course-${row.id}`}); cell.append(link); tr.append(cell);
    [num(m.lengthM, 0), m.cornerCount, num(m.straightFraction * 100, 0), num(m.minWidthW, 1), m.overtakeZones, num(sm.overtakesPerFieldLap, 1), num(sm.contactsPerCarKm, 1), num(sm.earlyLeadWreckRate * 100, 1), failed.length].forEach(x => tr.append(make('td', x))); $('matrix').append(tr);
    const card = make('article', '', {class: 'card', id: `course-${row.id}`, 'data-direction': row.id, 'data-label': row.name, 'data-samples': `${row.id} / ${sim.trialCount} seeded races / ${data.version}`});
    const top = make('div', '', {class: 'card-title'}); top.append(make('h2', row.name), make('span', row.course.theme, {class: 'badge'})); card.append(top, make('p', row.course.lesson, {class: 'small'}));
    if (row.arena) card.append(make('p', 'Shared Crown layout · six-car elimination stress mode · not the campaign finale setup', {class: 'notice small'}));
    const tags = make('div', '', {class: 'tags'}); g.tags.forEach(t => tags.append(make('span', t, {class: 'tag'}))); card.append(tags);
    const canvas = make('canvas', '', {class: 'track-map', role: 'img'}), legend = make('p', '', {class: 'map-legend'}); card.append(canvas, legend);
    const metrics = make('div', '', {class: 'track-metrics'});
    [[num(m.lengthM, 0), 'metres / lap'], [num(m.minWidthW, 1), 'minimum car widths'], [m.cornerCount, 'meaningful corners'], [m.overtakeZones, 'passing zone candidates'], [num(sm.overtakesPerFieldLap, 1), 'passes / field lap'], [num(sm.earlyLeadWreckRate * 100, 1) + '%', 'AI lead early wrecks']].forEach(([v, label]) => { const d = make('div'); d.append(make('strong', v), make('small', label)); metrics.append(d); }); card.append(metrics);
    const verdict = make('p', `${failed.length} design flag${failed.length === 1 ? '' : 's'} · ${g.lint.length ? g.lint.length + ' structural errors' : 'structural lint clear'} · deterministic replay ${row.deterministicReplay ? 'passed' : 'FAILED'}`, {class: failed.length || g.lint.length ? 'notice' : 'pass'}); card.append(verdict);
    card.append(details('Gates and hypotheses', make('p', 'These are authored diagnostic targets. No owner preference is inferred.', {class: 'small'}), table(['Gate', 'Measured', 'Target', 'Result / hypothesis'], gates(row).map(gate => [gate.metric, `${num(gate.value)} ${gate.unit}`, `${gate.min === null ? '—' : num(gate.min)} … ${gate.max === null ? '—' : num(gate.max)}`, `${gate.status.toUpperCase()} · ${gate.hypothesis}`])), ...g.lint.map(s => make('p', s, {class: 'fail'}))));
    card.append(details('Reference laps and campaign uses', make('p', 'One stock car driven by Pro AI; no opponents or combat. The second completed lap is the flying lap. Ineligible tiers are diagnostic only.', {class: 'small'}), table(['Tier / car', 'Standing lap s', 'Flying lap s', 'Pool / outcome'], row.referenceLaps.map(r => [`${r.tier} · ${r.car}`, num(r.standingLapSeconds), num(r.flyingLapSeconds), `${r.eligible ? 'eligible' : 'outside pool'} · ${r.timeout ? 'TIMEOUT' : 'finished'}`])), table(['Event', 'Tier', 'Laps', 'Phase / type'], row.events.map(e => [e.id, e.tier, e.laps, `${e.phase} / ${e.type}`])), make('p', 'Campaign duration is not measured by the three-lap instrument. Revalidate the actual event duration after the AI/pacing merge.', {class: 'small'})));
    card.append(details('Geometry, grammar and width profile', table(['Metric', 'Value'], Object.entries(m).map(([k, v]) => [k, num(v)])), table(['Arc fraction', 'Width m', 'Surface', 'Curvature /m'], g.profile.map(p => [num(p.fraction, 3), num(p.widthM, 1), p.surface, num(p.curvature, 4)])), table(['Corner start', 'Turn degrees', 'Min radius L', 'Tags'], g.corners.map(c => [num(c.start, 3), num(c.angleDegrees, 1), num(c.radiusL, 2), c.tags.join(' · ')])), make('p', `Radius sequence: ${g.radiusSequence.join(' → ')}. Histogram (arc-weighted): ${Object.entries(g.curvatureHistogram).map(([k, v]) => `${k} ${num(v * 100, 1)}%`).join(' · ')}`, {class: 'small'}), table(['Passing start', 'Length m', 'Width W', 'Approach → apex m/s'], g.overtakingZones.map(z => [num(z.start, 3), num(z.lengthM, 1), num(z.widthW, 1), `${num(z.approachMps, 1)} → ${num(z.apexMps, 1)}`]))));
    card.append(details('Surfaces, obstacles, pickups and risk lines', table(['Surface', 'Arc share'], Object.entries(g.surfaceFractions).map(([k, v]) => [k, num(v * 100, 1) + '%'])), table(['Obstacle effect', 'Count', 'Footprint m²'], Object.entries(g.obstacleLoad).map(([k, v]) => [k, v.count, num(v.footprintM2, 1)])), table(['Pickup / lap fraction', 'Reachable / risk', 'Clearance W', 'Observed collections'], g.pickups.map((p, i) => [`${p.kind} @ ${num(p.fraction, 3)}`, `${p.reachable ? 'yes' : 'NO'} / ${p.risk}`, num(p.clearanceW, 2), sim.pickupCollections[i]])), table(['Risk line start → end', 'Distance saved m', 'Grip ratio', 'Trade'], g.riskLines.map(r => [`${num(r.start, 3)} → ${num(r.end, 3)}`, num(r.savedDistanceM, 2), num(r.gripRatio, 2), r.validTrade ? 'geometric benefit + grip cost' : 'FLAG'])), make('p', 'Reachability is footprint clearance. A collected pickup proves access by the simulated field; neither establishes that the detour is worth taking.', {class: 'small'})));
    const interval = sim.earlyLeadWreck.wilson95;
    card.append(details('Race evidence, uncertainty and cross-checks', table(['Metric', 'Value'], Object.entries(sm).map(([k, v]) => [k, num(v)])), make('p', `${sim.earlyLeadWreck.count}/${sim.earlyLeadWreck.n} slot-0 early wrecks; descriptive Wilson 95% interval ${num(interval[0] * 100, 1)}–${num(interval[1] * 100, 1)}%. Rotations sharing a seed are correlated. This is an AI surrogate, not human fairness.`, {class: 'small'}),
      table(['Outcome', 'n', 'p10 s', 'p50 s', 'p90 s'], [['First wreck (observed only)', sim.firstWreckSeconds], ['Resolved trial duration', sim.finishedRaceSeconds], ['Car finish time', sim.carFinishSeconds]].map(([label, d]) => [label, d.n, num(d.p10), num(d.p50), num(d.p90)])),
      make('p', `${sim.timeouts} right-censored race timeouts; ${sim.noWreckCensored} no-wreck trials. ${sim.trapOpportunities} trap opportunity episodes; planned hunter behavior remains unmeasured.`, {class: 'small'}),
      table(['Rotation', 'Trials', 'Early wreck %'], sim.rotationRates.map(r => [r.rotation, r.n, num(r.earlyRate * 100, 1)])),
      make('p', `Independent seed halves: ${sim.seedSplit.status}, early-wreck rate difference ${num(sim.seedSplit.difference)} (tolerance ${sim.seedSplit.tolerance}). Identity rotation: ${sim.rotationCrossCheck.status}, spread ${num(sim.rotationCrossCheck.spread)}. Geometric 90° rotation ${row.worldRotation.geometryPass ? 'passed' : 'FAILED'}; reference lap delta ${num(row.worldRotation.referenceLapDeltaSeconds)} s, ${row.worldRotation.simulationStatus}.`, {class: 'small'})));
    card.append(details('Combat and hazard attribution', table(['Damage source', 'Damage HP', 'Wrecks'], Object.entries(sim.damageByKind).map(([kind, damage]) => [kind, num(damage, 1), sim.deathsByKind[kind]])), table(['Weapon', 'Shots / deployments'], Object.entries(sim.shotsByWeapon)), make('p', `${sim.solidSolverContacts} solid-obstacle solver contacts (not debounced episodes). ${g.hazardLoad.oilSpotCount} authored oil spots; ${num(g.hazardLoad.oilFootprintM2, 1)} m² summed oil footprint.`, {class: 'small'})));
    const sections = table(['Section %', 'Live car-s', 'Speed m/s', 'Contacts', 'Wrecks', 'Spins', 'Stuck', 'Passes', 'Trap proxy', 'Line bits'], sim.heat.exposureCarSeconds.map((e, i) => [num(i / 48 * 100, 1), num(e, 1), num(sim.heat.meanSpeedMps[i], 1), sim.heat.contacts[i], sim.heat.wrecks[i], sim.heat.spins[i], sim.heat.stuck[i], sim.heat.passes[i], sim.heat.trapOpportunities[i], num(sim.heat.lineEntropy[i])])); sections.classList.add('section-table'); card.append(details('Section heatmap values and exposure', sections));
    const labLink = make('a', 'Edit a draft in Track Lab', {href: `../lab/index.html?course=${encodeURIComponent(row.courseId)}`}); card.append(labLink);
    $('courses').append(card); views.push({row, card, canvas, legend});
  }
  const draw = () => { for (const v of views) if (!v.card.hidden) v.legend.textContent = TrackView.draw(v.canvas, v.row.course, {heat: v.row.simulation.heat, layer: $('layer').value}); };
  const filter = () => { const theme = $('theme-filter').value, search = $('search').value.toLowerCase(); for (const v of views) v.card.hidden = !(theme === 'all' || v.row.course.theme === theme) || ![v.row.name, v.row.course.lesson, ...v.row.geometry.tags].join(' ').toLowerCase().includes(search); $('visible-count').textContent = `${views.filter(v => !v.card.hidden).length} / ${views.length} views`; draw(); };
  $('theme-filter').addEventListener('change', filter); $('search').addEventListener('input', filter); $('layer').addEventListener('change', draw); window.addEventListener('resize', draw);
  filter(); window.atlasReady = true;
})();
