(() => {
 'use strict';const data=window.TRACK_CANDIDATES,$=id=>document.getElementById(id),el=(tag,text,attrs={})=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);return e},num=(n,d=1)=>Number.isFinite(n)?n.toFixed(d):'unmeasured';
 $('truth').textContent=data.truth;const candidates=data.candidates,slots=[...new Set(candidates.map(c=>c.slot))],divisions=['scrap','foundry','salt','switchback','crown'];
 $('summary').textContent=`${candidates.filter(c=>!c.accepted).length}/${data.expectedCandidates} new choices · ${slots.length}/${data.expectedSlots} stable slots · ${candidates.filter(c=>c.technicalStatus==='proved').length} pass the race contract · ${data.pairs.filter(p=>p.similar).length} similar outline pairs. Human feel and Stick status are recorded in the R3 design note.`;
 function outline(ctx,c,x,y,w,h,color='#176978') {
  const ps=c.shape.outline,extra=(c.course.branches||[]).flatMap(b=>b.ribbon),all=[...ps,...extra],xs=all.map(p=>p[0]),ys=all.map(p=>p[1]),loX=Math.min(...xs),hiX=Math.max(...xs),loY=Math.min(...ys),hiY=Math.max(...ys),scale=Math.min((w-28)/(hiX-loX),(h-24)/(hiY-loY));
  const xy=p=>[x+w/2+(p[0]-(loX+hiX)/2)*scale,y+h/2-(p[1]-(loY+hiY)/2)*scale];ctx.lineWidth=2.5;ctx.strokeStyle=color;ctx.beginPath();ps.forEach((p,i)=>i?ctx.lineTo(...xy(p)):ctx.moveTo(...xy(p)));ctx.closePath();ctx.stroke();
  for(const branch of c.course.branches||[]){ctx.strokeStyle='#697c88';ctx.beginPath();branch.ribbon.forEach((p,i)=>i?ctx.lineTo(...xy(p)):ctx.moveTo(...xy(p)));ctx.stroke()}
  for(const j of c.course.junctions||[]){const p=TrackView.point(c.course,j[0]);ctx.fillStyle='#aa7020';ctx.font='bold 14px sans-serif';ctx.fillText('J',...xy(p))}
 }
 for(const division of divisions) {
  const rows=slots.filter(s=>s.startsWith(division+'-'));if(!rows.length)continue;const section=el('section',null,{'class':'sheet-section','data-division':division});section.append(el('h2',division+' — outline choices',{'class':'sheet-heading'}));const sheet=el('canvas',null,{id:`sheet-${division}`,class:'sheet','aria-label':`${division} candidate outline sheet`});sheet.width=1260;sheet.height=rows.length*250;const ctx=sheet.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,sheet.width,sheet.height);
  rows.forEach((slot,row)=>candidates.filter(c=>c.slot===slot).forEach((c,col)=>{const x=col*420,y=row*250;outline(ctx,c,x,y+35,420,200);ctx.fillStyle=c.accepted?'#246536':'#222';ctx.textAlign='center';ctx.font='bold 16px sans-serif';ctx.fillText(c.id+(c.accepted?' · KEEP':''),x+210,y+20);ctx.font='13px sans-serif';ctx.fillText(c.family,x+210,y+39)}));section.append(sheet);$('sheets').append(section);
 }
 if(data.hunterEvidence){const section=$('hunter-evidence');section.append(el('h2','Observed hunter pressure'),el('p',data.hunterEvidence.definition),el('a','Raw episodes and replay coordinates',{href:'../candidates/hunter-evidence.json'}));const table=el('table');for(const episode of data.hunterEvidence.episodes){const row=el('tr');row.append(el('th',episode.candidate),el('td',episode.tactic+' at '+num(episode.seconds)+' s; seed '+episode.seed+' / rotation '+episode.rotation+'; hunter '+episode.hunter+' targeting leader '+episode.leader+'; '+num(episode.leaderSpeedMps)+' m/s; hold '+num(episode.holdSeconds)+' s.'));table.append(row)}section.append(table)}
 if(data.activeHunterEvidence)$('hunter-evidence').append(el('p',`${data.activeHunterEvidence.episodes.length} active corner-block episodes observed in ${data.activeHunterEvidence.checkedTrials} focused trials. The pursuit episodes above do not establish deliberate blocking.`),el('a','Focused blocking check',{href:'../candidates/hunter-active-evidence.json'}));
 const views=[];
 for(const slot of slots) {
  const group=el('section',null,{class:'slot','data-slot':slot});group.append(el('h2',slot));const cards=el('div',null,{class:'track-cards'});group.append(cards);
  for(const c of candidates.filter(c=>c.slot===slot)) {
   const region=window.REGION_DATA.regions.find(r=>r.id===window.REGION_DATA.candidateRegions[c.id]);c.course.region=region.id;c.course.regionName=region.name;
   const card=el('article',null,{class:'card','data-direction':c.id,'data-label':`${c.slot} / ${c.id} / ${c.family}`,'data-samples':`${c.id}; ${c.course.theme}; tier ${c.tier}; ${c.laps} laps; ${c.role}; recipe + CSV bundle`});card.dataset.region=region.id;card.dataset.samples+=`; region ${region.id} / ${region.name}`;card.dataset.theme=c.course.theme;card.dataset.search=[c.id,c.family,c.role,c.course.theme].join(' ').toLowerCase();card.append(el('h3',c.accepted?'Runoff — accepted':`${c.id.at(-1).toUpperCase()} · ${c.family}`,{class:'candidate-label'}),el('p',`${c.course.theme} · ${c.role} · tier ${c.tier} · ${c.role==='arena'?'elimination':c.laps+' laps'}${c.role!=='arena'&&c.laps!==c.oldLaps?` (was ${c.oldLaps})`:''}`));
   if(c.accepted)card.dataset.ownerAccepted='true';
   const status=c.accepted?'Owner Keep retained. Original course data. Baseline flags: '+(c.proof?.flags?.join(', ')||'none measured')+'.':c.proof?.seeds===12?(c.technicalStatus==='proved'?'Geometry and 72-trial proof pass.':'Technical flags: '+c.technicalFlags.join(', ')):c.proof?`Initial ${c.proof.sixCarTrials}-trial probe; full evidence pending.`:'Simulation pending.';card.dataset.samples+='; '+status;card.append(el('p',status,{class:`status-line ${c.technicalStatus==='proved'?'pass':'fail'}`}));
   const map=el('canvas',null,{class:'candidate-map'}),legend=el('p','',{class:'legend'});card.append(map,legend);views.push({c,map,legend,card});
   card.append(el('p',Object.entries(c.shape.histogram).filter(([,n])=>n).map(([k,n])=>`${n} ${k}`).join(' · ')));
   const metrics=c.shape.metrics,g=c.geometry?.metrics||{},table=el('table');const rows=[['Road / radius',`${num(metrics.lengthM,0)} m / ${num(g.minRadiusL,2)} L min`],['Width range',`${num(g.minWidthW,2)}–${num(g.maxWidthW,2)} W`],['Hull packing',`${num(metrics.hullPerimeterRatio,2)} perimeter / ${num(metrics.hullAreaPacking,2)} area`],['Reversals / turn changes',`${metrics.directionReversals} / ${metrics.signChanges}`],['Fold-back / near road',`${num(metrics.foldbackRatio*100)}% / ${num(metrics.proximityRatio*100)}%`],['Junctions / branches',`${c.course.junctions?.length||0} / ${c.course.branches?.length||0}`],['Nearest outline',c.nearest?`${num(c.nearest.outlineDistance,3)} (floor ${data.outlineThresholds.outlineDistance})`:'accepted exception'],['Authoring reference',`${num(c.referenceSeconds)} s / target ${c.minSeconds??'—'}–${c.maxSeconds??'—'} s`]];
   card.append(el('p',`Region: ${region.name} / ${region.climate}`,{class:'region-assignment'}));card.append(el('p',c.course.lesson||''));const proof=c.proof,agg=proof?.aggregate;if(proof)rows.push(['Clean six-car finish',`${num(proof.cleanFinishSeconds?.p50)} s median`],[c.role==='arena'?'Six-car rehearsal lap winner':'Combat lap winner',`${num(proof.lapWinnerSeconds?.p50)} s median; ${proof.lapWinnerSeconds?.n}/${proof.sixCarTrials}`],['Passes / contacts',`${agg.overtakes} / ${agg.contactEpisodes}`],['Early lead-slot wreck',`${num(agg.earlyLeadWreck.rate*100)}% (${agg.earlyLeadWreck.count}/${agg.earlyLeadWreck.n})`],['3 s stalls / timeouts',`${agg.stuck} / ${agg.timeouts}`],['Hunter intent damage',num(proof.hunter.huntIntentDamage)],['Seed / rotation cross-check',`${agg.seedSplit.status} / ${agg.rotationCrossCheck.status}`],['Determinism / rotation',`${proof.repeatHashMatches?'same hash':'FAIL'} / Δ ${num(proof.rotationReferenceDifferenceSeconds,3)} s`]);
   if(c.role==='arena'){rows.push(['Actual campaign duel',c.duelProof?`${c.duelProof.wins}/${c.duelProof.trials.length} resolved; ${c.duelProof.timeouts} timeouts`:'pending'],['Arena evidence scope','Six-car lap rehearsal plus separate two-car campaign duel.']);}for(const [a,b]of rows){const tr=el('tr');tr.append(el('th',a),el('td',b));table.append(tr)}card.append(table);
   const signature=el('canvas',null,{class:'candidate-signature','aria-label':'Signed turn along the lap'});signature.width=500;signature.height=70;const sx=signature.getContext('2d');sx.fillStyle='#fff';sx.fillRect(0,0,500,70);sx.strokeStyle='#aaa';sx.beginPath();sx.moveTo(0,35);sx.lineTo(500,35);sx.stroke();sx.strokeStyle='#a04a1a';sx.beginPath();c.shape.turningSignature.forEach((v,i)=>i?sx.lineTo(i/255*500,35-v*110):sx.moveTo(0,35-v*110));sx.stroke();card.append(el('p','Signed-turn signature'),signature);
   const detail=el('details');detail.append(el('summary','Corner sequence and gates'),el('pre',c.shape.corners.map(k=>`${num(k.start*100)}%: ${k.type}; ${num(k.degrees)}°; R ${num(k.radiusL,2)} L`).join('\n')),el('pre',[...c.shape.gates,...(c.gates||[])].map(g=>`${g.status}: ${g.metric} = ${num(g.value,3)}`).join('\n')));card.append(detail);
   const before=el('details');before.append(el('summary','Previous outline for this event'));const old=el('canvas',null,{class:'before-map'});old.width=500;old.height=200;const ox=old.getContext('2d');ox.fillStyle='#fff';ox.fillRect(0,0,500,200);const oldC={...c,shape:{outline:c.before.ribbon.map(p=>p.slice(0,2))},course:c.before};outline(ox,oldC,0,0,500,200,'#a64935');before.append(old);card.append(before);
   if(!c.accepted){const links=el('p',null,{class:'candidate-links'});links.append(el('a','Recipe',{href:`../candidates/recipes/${c.id}.csv`}),el('a','CSV bundle',{href:`../candidates/bundles/${c.id}.zip`}),el('a','Open in Lab',{href:`../lab/index.html?candidate=${c.id}`}));if(c.duelProof)links.append(el('a','Actual duel evidence',{href:`../candidates/${c.id}-duel.json`}));if(c.role==='arena')links.append(el('a','Rejected earlier elimination stress',{href:`../../evidence/tracks/r3/arena-initial/${c.id}.json`}));if(c.proofFile)links.append(el('a','Proof',{href:c.proofFile}));card.append(links)}cards.append(card);
  }
  $('courses').append(group);
 }
 function draw(){for(const {c,map,legend,card}of views)if(!card.hidden&&!card.closest('.slot').hidden)legend.textContent=TrackView.draw(map,c.course,{heat:c.proof?.aggregate?.heat,layer:$('layer').value})}
 function filter(){for(const v of views){const division=v.c.slot.replace(/-\d+$/,'');v.card.hidden=($('division').value!=='all'&&division!==$('division').value)||($('road-theme').value!=='all'&&v.c.course.theme!==$('road-theme').value)||!v.card.dataset.search.includes($('search').value.toLowerCase())}for(const group of document.querySelectorAll('.slot'))group.hidden=![...group.querySelectorAll('.card')].some(c=>!c.hidden);for(const sheet of document.querySelectorAll('.sheet-section'))sheet.hidden=$('division').value!=='all'&&sheet.dataset.division!==$('division').value;draw()}
 for(const id of ['division','road-theme','layer'])$(id).addEventListener('change',filter);$('search').addEventListener('input',filter);window.addEventListener('resize',draw);draw();window.candidatesReady=true;
})();
